name: go-ci

on: workflow_dispatch

jobs:
  full_ci:  # full ci job
    strategy:  # Matrix for different go versions
      matrix:
        go_version: [ 1.22.4 ]  # current go version used for the project

    runs-on: ubuntu-20.04

    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
